In [26]:
import pandas as pd
df1=pd.read_csv('world.csv')
df2=df1[['洲名','國家','日期','總確診數','新增確診數']]
df3=df2.query('國家=="台灣"')
df3
df3.sort_values(by='新增確診數',ascending=False)[:5]

        洲名  國家          日期     總確診數   新增確診數
164835  亞洲  台灣  2022-05-14   699824  128954
164830  亞洲  台灣  2022-05-09   397504  128935
164848  亞洲  台灣  2022-05-27  1735067   94796
164840  亞洲  台灣  2022-05-19  1070561   89420
164846  亞洲  台灣  2022-05-25  1558380   89361

In [19]:
df3.set_index("日期") #inplace=False 假換，不會蓋掉原本的df3；inplace=True 真換，會蓋掉原本的df3

,ID,iso_code,洲名,國家,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
日期,,,,,,,,,,,,,,,,,,,,,
2022-05-14,164836,TWN,亞洲,台灣,699824,128954,61607.857,1049,81,21.857,...,76312.0,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24
2022-05-09,164831,TWN,亞洲,台灣,397504,128935,37792.714,931,35,9.000,...,87600.0,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86
2022-05-27,164849,TWN,亞洲,台灣,1735067,94796,82682.286,1784,126,71.429,...,83406.0,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08
2022-05-19,164841,TWN,亞洲,台灣,1070561,89420,71384.429,1235,59,38.143,...,75623.0,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25
2022-05-25,164847,TWN,亞洲,台灣,1558380,89361,82462.714,1554,76,54.000,...,71461.0,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-15,164017,TWN,亞洲,台灣,18,0,0.143,0,0,0.000,...,0.0,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,99999.00
2020-02-18,164020,TWN,亞洲,台灣,22,0,0.571,1,0,0.000,...,0.0,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,10.52
2020-01-18,163989,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
2020-01-17,163988,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
2020-01-16,163987,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00